services:
    mongo_db:
        image: mongo:6.0
        restart: always
        command: [--auth]
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USR}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PWD}
            MONGO_INITDB_DATABASE: testDB
            MONGO_INITDB_ACCESS_USR: ${MONGO_INITDB_USR}
            MONGO_INITDB_ACCESS_PWD: ${MONGO_INITDB_PWD}
            MONGODB_IP: ${MONGODB_IP}
            MONGODB_PORT: ${MONGODB_PORT}
        ports:
            - ${MONGODB_PORT}:27017
        volumes:
            - ./mongoinit:/docker-entrypoint-initdb.d

    mongo-seed:
        build: 
            context: ./seed
            args: 
                MONGO_CONTAINER: mongo_db
                MONGO_CONTAINER_PORT: 27017
                MONGO_USER: ${MONGO_INITDB_USR}
                MONGO_PASSWORD: ${MONGO_INITDB_PWD}
        depends_on:
            - mongo_db